export { default as Header } from "./Header.astro";
export { default as Hero } from "./Hero.astro";
export { default as Footer } from "./Footer.astro";
export { default as Faq } from "./Faq.astro";
export { default as About } from "./About.astro";
export { default as Event } from "./Event.astro";
export { PoweredBy } from "./poweredBy";
export { Timeline } from "./timeline";
export { Experts } from "./experts";
export { Challenge } from "./challenge";
export { Prizes } from "./prizes";
export { Guidelines } from "./guidelines";
